name: feed-sieve
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6677:6677
    volumes:
      - ./rules.yaml:/app/rules.yaml:ro
      - ./appsettings.Local.json:/app/appsettings.Local.json:ro
