name: feed-sieve
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6677:6677
    volumes:
      - ./rules.default.yaml:/app/rules.default.yaml:ro
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
