services:
  feed-sieve-prod:
    container_name: feed-sieve-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9010:5000
    volumes:
      - ./rules.yaml:/app/rules.yaml:rw
